import { Button } from "@mantine/core";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-3xl text-red-500 font-bold underline">
          Hello world!
        </h1>
        <Button component="a" className="ml-4">
          Next link button
        </Button>
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
